# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NORjKvQm_6pcxOTUZWMMxzoKN-PLdbeU
"""

from .losses import SimCLR_Loss, ProtoNetLoss
from .metrics import evaluate

__all__ = [
    'SimCLR_Loss',
    'ProtoNetLoss',
    'evaluate'
]