# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4J42q5TEsCCfxs4zCwVVqmNyBO7lOFi
"""

from .simclr_train import train_simclr
from .protonet_train import train_protonet

__all__ = [
    'train_simclr',
    'train_protonet'
]